version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.7.9
    executor: python/default
    steps:
      - checkout
      - run:
         name: "Install system dependencies"
         command: |
              sudo apt-get update && sudo apt-get install -y postgresql postgresql-server-dev-all postgresql-client pgxnclient libgmp3-dev libmpc-dev libmpfr-dev
              sudo pgxn install pgmp
      - run:
         name: "Run tests"
         command: |
              pip install -r requirements-dev.txt
              pytest --mypy
workflows:
  main:
    jobs:
      - build-and-test

